##
# Nginx configuration for pinfinity
# On the Raspberry Pi, this file is located at `/etc/nginx/sites-available/default`.
# This file is not used, just for information, because we run uvicorn directly.
##
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /home/infinity/certs/cert.pem;
    ssl_certificate_key /home/infinity/certs/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
